version: "3.2"
services:
  debug-backend:   # DEBUG
    build:
      context: ./SkyManager-Backend
      target: dev
    ports:
      - 8451:80
      # - 4433:443
    volumes:
      - ./SkyManager-Backend/:/usr/src/app
      # - ./test-ssl/:/usr/src/app/sslcert
    environment:
      DB_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MASTER_KEY: ${MASTER_KEY}  # Enrcypt for Customer Passes
      MODE: TEST   # SQL Output
      FRONTEND_URL: ${FRONTEND_URL}
      SHOW_API_DOCS: 1
      # SSL_KEY: "privateKey.key"
      # SSL_CERT: "certificate.crt"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot" , "-pexample" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8084:80
    restart: always