version: "3.2"
services:
  skymanager-backend:
    image: skyface753/skymanager
    ports:
      - 8452:80
    environment:
      DB_HOST: db                       
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MASTER_KEY: ${MASTER_KEY}  # Enrcypt for Customer Passes
      FRONTEND_URL: ${FRONTEND_URL}
    restart: always
    depends_on:
      db:
        condition: service_healthy

  skymanager-frontend:
    image: skyface753/skymanager-frontend
    ports:
      - 8091:80
    environment:
      BACKEND_URL: "https://skymanager.skyface.de"
    
  db:
    image: mariadb
    restart: always
    volumes:
      - ./DB-Data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: exampleeee
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot" , "-pexampleeee" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  db-cron-backup:
    image: fradelg/mysql-cron-backup
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASS: exampleeee
      INIT_BACKUP: "1"
      MAX_BACKUPS: 5
      TZ: "Europe/Berlin"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backup:/backup


  

