version: "3.2"
services:
  skymanager-backend:
    image: skyface753/skymanager
    ports:
      - 8080:80
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      DB_HOST: db-service
      MYSQL_USER: dbUser
      MYSQL_DATABASE: dbName
      MYSQL_PASSWORD: dbPass
      MASTER_KEY: MasterKey
    restart: always
    depends_on:
      db-service:
        condition: service_healthy

  skymanager-frontend:
    image: skyface753/skymanager-frontend
    ports:
      - 80:80
    
  db-service:
    image: mariadb
    restart: always
    volumes:
      - ./DB-Data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOTMYSQL
      MYSQL_DATABASE: dbName
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPass
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot" , "-pROOTMYSQL" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10